spring.application.name=SMS

spring.datasource.url=jdbc:postgresql://localhost:5432/SMS
spring.datasource.username=postgres
spring.datasource.password=Saiteja@1919
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS
jwt.expiration-ms=86400000